widgets:
  -
      # Where should the widget be placed, left sidebar or right sidebar
      position: left
      type: profile
      # Author name
      author: YH
      # Author title
      author_title: Web Developer
      # Author's current location
      location: Taipei, Taiwan
      # URL or path to the avatar image
      avatar: /gallery/YH.svg
      # Whether show the rounded avatar image
      avatar_rounded: false
      # Email address for the Gravatar
      gravatar: 
      # URL or path for the follow button
      follow_link: 
      # Links to be shown on the bottom of the profile widget
      social_links:
          Github:
              icon: fab fa-github
              url: 'https://github.com/williamyhhuang'
          LinkedIn:
              icon: fab fa-linkedin
              url: 'https://www.linkedin.com/in/yh-huang-70826421b/'
      # Where should the widget be placed, left sidebar or right sidebar
  # Recent posts widget configurations
  -
      # Where should the widget be placed, left sidebar or right sidebar
      position: left
      type: recent_posts
  -
      position: left
      type: categories
  # Archives widget configurations
  -
      # Where should the widget be placed, left sidebar or right sidebar
      position: left
      type: archives
  # Tags widget configurations
  -
      # Where should the widget be placed, left sidebar or right sidebar
      position: left
      type: tags